### PR TITLE
Margin vs Padding lighting talk

### PR DESCRIPTION
**Pull request by Splitxorpio**

### CODE REVIEW

**Comment by tregsthedev** [comment]
👋 Hey Arnav! Thank you so much for submitting your PR for your workshop!

I really love the idea you have, and I've heard quite a lot about it from others! The video from Epoch BA was also pretty nice! A couple things I wanted to mention/ask:

- Noticed that you edited the master file, instead of editing it and putting it in the workshop folder. Is there anything I can help if you're a little stuck or confused on how to do this?
- I feel that this would work better as a lighting talk, rather than a workshop because of how there doesn't seem to be an end-product. I think this would make a good lighting talk where you would talk about the differences between margin and padding with the examples you already have for your workshop

Would you be interested in switching it up?

**Comment by Splitxorpio** [comment]
Sure thing, we can switch it up to a lightning talk. I will also move it to the folder, completely forgot to do that

**Comment by Splitxorpio** [comment]
Just updated it

**Review by tregsthedev — APPROVED** [review]
this looks awesome!

**Comment by tregsthedev** [comment]
:tada: I can't wait to see your lighting talk! I will be reaching out over this weekend with some more stuff :D

**Comment by tregsthedev** [comment]
actually, reverting this for now! you're still set, but could you resubmit and move this to the lighting talks folder with the PR being your_name.md? This is fine as lighting talk! Sorry for making you change it!!

**Pull request merged**
