### PR TITLE
Fix duplicate cafe orpheus guild listing

### PR DESCRIPTION
**Pull request by Soar1826**
@alexdevz pls merge this fix - not a guild. thx!

### CODE REVIEW

**Comment by cfanoulis** [comment]
duplicate of #11 ???

**Comment by Soar1826** [comment]
@cfanoulis This change includes the newer guilds

**Comment by cfanoulis** [comment]
I'd rather merge main in my PR and keep duplicates out. If you have more changes please edit your PR accordingly

**Comment by Soar1826** [comment]
@cfanoulis @alexdevz resolved on slack - github was being weird as usual https://hackclub.slack.com/archives/C054FA87K8C/p1685338712229789?thread_ts=1685338452.143949&cid=C054FA87K8C

**Comment by Soar1826** [comment]
Reopen

**Pull request closed without merging**
