### PR TITLE
Minecraft Lightning Talk

### PR DESCRIPTION
**Pull request by SerenityUX**

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
love it! let's do it.

**Review by tregsthedev — APPROVED** [review]

**Comment by tregsthedev** [comment]
@SerenityUX going to merge this but there's some git conflicts! Could you fix these up and then send me a DM on slack?

**Comment by SerenityUX** [comment]
I fixed the pr_lightning.md

**Review by SerenityUX — COMMENTED** [review]
fixed PR issue

**Comment by tregsthedev** [comment]
can you add a pr_lighting.md file? just leave it blank, I think that might be the issue?

**Review by SerenityUX — COMMENTED** [review]
Fixed

**Pull request merged**
