### PR TITLE
lightning talk

### PR DESCRIPTION
**Pull request by reesericci**
:zap:

### CODE REVIEW

**Comment by tregsthedev** [comment]
Hi! Could you please convert this into a draft PR or close and resubmit when you have more of a plan? We're looking for a little more information for each lighting talk :)

**Comment by tregsthedev** [comment]
Hi Reese!

I'm going to go ahead and convert this PR to a draft PR. I love your idea to host a lighting talk on Public tranist, but we need a little bit more information from you on what you want to talk about. It can be a little more detailed, and we're just looking for some jot notes on ideas or things you would bring up.

Would you be okay with editing your file?

**Comment by reesericci** [comment]
No. I want to do the talk kinda on the spot.

**Comment by reesericci** [comment]
No. I want to do the talk kinda on the spot.

**Comment by tregsthedev** [comment]
@reesericci

**Comment by reesericci** [comment]
I edited my file to talk more about what I want to say

**Review by sampoder — APPROVED** [review]
LGTM

**Comment by tregsthedev** [comment]
:tada: I can't wait to see your lighting talk! I will be reaching out over this weekend with some more stuff :D

**Pull request merged**
