### PR TITLE
distrobox lightning talk

### PR DESCRIPTION
**Pull request by PizzaLovingNerd**

### CODE REVIEW

**Review by reesericci — APPROVED** [review]

**Comment by tregsthedev** [comment]
👋 Hi @PizzaLovingNerd!

Thank you for submitting your PR! I really like the idea of doing something with DistroBox! I haven't heard about it before, but it sounds really cool. The only I have is that it feels better suited as a workshop rather than a lighting talk.

With the stuff you want to cover, I think it would make a cool workshop. Would you be interested in that & do you have any ideas of what you run a workshop on using Distrobox or other tools along with it?

**Review by tregsthedev — CHANGES_REQUESTED** [review]
see comment above for changes requested (had to add something here to add this label)

**Comment by PizzaLovingNerd** [comment]
I can’t really think of anything to showcase for DistroBox other than simply installing software through it and maybe setting up a dev environment. The problem is I can’t think of enough things to make it an interactive workshop which is why I went for a lighting talk.

**Comment by tregsthedev** [comment]
Hi @PizzaLovingNerd,

I'm going to go ahead and close this for now! I don't think this will quite work as a lighting talk, but if you're interested in running another workshop or lighting talk, feel free to submit a new PR!

Hope to see you at Outernet,
Arav

**Pull request closed without merging**
